# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Genotype.create([
  { :person_id => "1", :snp_id => "1", :data => "AG", :created_at => "2013-01-10 08:38:26", :updated_at => "2013-01-10 08:38:26", :personid => "SP1_MOTHER_V3" },
  { :person_id => "1", :snp_id => "1", :data => "GG", :created_at => "2013-01-10 08:38:26", :updated_at => "2013-01-10 08:38:26", :personid => "SP1_FATHER_V3" },
  { :person_id => "1", :snp_id => "2", :data => "AA", :created_at => "2013-01-10 08:38:26", :updated_at => "2013-01-10 08:38:26", :personid => "SP1_MOTHER_V3" },
  { :person_id => "1", :snp_id => "2", :data => "AA", :created_at => "2013-01-10 08:38:26", :updated_at => "2013-01-10 08:38:26", :personid => "SP1_FATHER_V3" },
  { :person_id => "1", :snp_id => "3", :data => "CC", :created_at => "2013-01-10 08:38:27", :updated_at => "2013-01-10 08:38:27", :personid => "SP1_MOTHER_V3" },
  { :person_id => "1", :snp_id => "3", :data => "CC", :created_at => "2013-01-10 08:38:27", :updated_at => "2013-01-10 08:38:27", :personid => "SP1_FATHER_V3" },
  { :person_id => "1", :snp_id => "4", :data => "GG", :created_at => "2013-01-10 08:38:28", :updated_at => "2013-01-10 08:38:28", :personid => "SP1_MOTHER_V3" },
  { :person_id => "1", :snp_id => "4", :data => "G", :created_at => "2013-01-10 08:38:28", :updated_at => "2013-01-10 08:38:28", :personid => "SP1_FATHER_V3" },
  { :person_id => "1", :snp_id => "5", :data => "AT", :created_at => "2013-01-10 08:38:28", :updated_at => "2013-01-10 08:38:28", :personid => "SP1_MOTHER_V3" },
  { :person_id => "1", :snp_id => "5", :data => "AA", :created_at => "2013-01-10 08:38:28", :updated_at => "2013-01-10 08:38:28", :personid => "SP1_FATHER_V3" },
  { :person_id => "1", :snp_id => "6", :data => "GG", :created_at => "2013-01-10 08:38:29", :updated_at => "2013-01-10 08:38:29", :personid => "SP1_MOTHER_V3" },
  { :person_id => "1", :snp_id => "6", :data => "GG", :created_at => "2013-01-10 08:38:29", :updated_at => "2013-01-10 08:38:29", :personid => "SP1_FATHER_V3" }
], :without_protection => true )



Snp.create([
  { :name => "rs17646946", :description => "curliness", :cc => nil, :cg => nil, :gg => "In Europeans, slightly curlier hair on average", :ag => "In Europeans, straighter hair on average", :aa => "In Europeans, straighter hair on average", :gt => nil, :tt => nil, :ct => nil, :at => nil, :created_at => "2013-01-10 08:37:31", :updated_at => "2013-01-10 08:37:31" },
  { :name => "rs3827760", :description => "thickness", :cc => nil, :cg => nil, :gg => nil, :ag => "Thinner than typical Asian hair", :aa => "Typical European or African hair thickness", :gt => nil, :tt => nil, :ct => nil, :at => nil, :created_at => "2013-01-10 08:37:31", :updated_at => "2013-01-10 08:37:31" },
  { :name => "rs1805007", :description => "redness", :cc => "Typical odds of having red hair", :cg => nil, :gg => nil, :ag => nil, :aa => nil, :gt => nil, :tt => "Greatly increased odds of having red hair", :ct => "Substantially higher odds of having red hair", :at => nil, :created_at => "2013-01-10 08:37:31", :updated_at => "2013-01-10 08:37:31" },
  { :name => "rs6152", :description => "baldness", :cc => nil, :cg => nil, :gg => "able to go bald", :ag => "If male, won't go bald", :aa => "Won't go bald", :gt => nil, :tt => nil, :ct => nil, :at => nil, :created_at => "2013-01-10 08:37:31", :updated_at => "2013-01-10 08:37:31" },
  { :name => "rs11803731", :description => "curliness", :cc => nil, :cg => nil, :gg => nil, :ag => nil, :aa => "Straighter hair", :gt => nil, :tt => "Curlier hair", :ct => nil, :at => nil, :created_at => "2013-01-10 08:37:31", :updated_at => "2013-01-10 08:37:31" },
  { :name => "rs16891982", :description => "color", :cc => "Generally non-European, but if European, 7x more likely to have black hair", :cg => nil, :gg => "Generally european", :ag => nil, :aa => nil, :gt => nil, :tt => nil, :ct => nil, :at => nil, :created_at => "2013-01-10 08:37:31", :updated_at => "2013-01-10 08:37:31" }
], :without_protection => true )


